spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/foro_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: clave_super_secreta_enterprise_2026
